<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Alumni;
use Carbon\Carbon;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alumni = [
            [
                'name' => 'Rahul Sharma',
                'email' => 'rahul.sharma@microsoft.com',
                'phone' => '+91 98765 43210',
                'student_id' => 'SNC2016001',
                'course' => 'B.Tech',
                'branch' => 'Computer Science Engineering',
                'passing_year' => 2020,
                'admission_year' => 2016,
                'current_company' => 'Microsoft',
                'current_position' => 'Senior Software Engineer',
                'current_location' => 'Hyderabad, India',
                'current_salary' => 1800000.00,
                'bio' => 'Passionate software engineer with expertise in cloud computing and AI. Leading multiple projects at Microsoft and mentoring junior developers.',
                'testimonial' => 'Shantineketan College provided me with the foundation and skills needed to excel in the tech industry. The faculty support was exceptional and the practical approach to learning helped me secure my dream job.',
                'linkedin_url' => 'https://linkedin.com/in/rahulsharma',
                'twitter_url' => 'https://twitter.com/rahulsharma',
                'achievements' => ['Microsoft MVP Award 2023', 'Best Employee Award 2022', 'Published 5 research papers'],
                'skills' => ['C#', '.NET', 'Azure', 'Machine Learning', 'Python', 'JavaScript'],
                'is_featured' => true,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => true,
                'experience_years' => 4,
                'industry' => 'Information Technology',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Priya Patel',
                'email' => 'priya.patel@tcs.com',
                'phone' => '+91 87654 32109',
                'student_id' => 'SNC2017002',
                'course' => 'MBA',
                'branch' => 'Finance',
                'passing_year' => 2019,
                'admission_year' => 2017,
                'current_company' => 'Tata Consultancy Services',
                'current_position' => 'Business Analyst',
                'current_location' => 'Mumbai, India',
                'current_salary' => 1200000.00,
                'bio' => 'Business analyst with strong analytical skills and experience in financial modeling. Specialized in digital transformation projects.',
                'testimonial' => 'The MBA program at Shantineketan College equipped me with practical business knowledge and leadership skills that I use every day in my corporate career.',
                'linkedin_url' => 'https://linkedin.com/in/priyapatel',
                'achievements' => ['TCS Excellence Award 2022', 'Certified Business Analyst', 'Led 10+ successful projects'],
                'skills' => ['Business Analysis', 'Financial Modeling', 'Project Management', 'SQL', 'Tableau'],
                'is_featured' => true,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => true,
                'experience_years' => 5,
                'industry' => 'Consulting',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Amit Kumar',
                'email' => 'amit@innovatetech.com',
                'phone' => '+91 76543 21098',
                'student_id' => 'SNC2014003',
                'course' => 'B.Tech',
                'branch' => 'Mechanical Engineering',
                'passing_year' => 2018,
                'admission_year' => 2014,
                'current_company' => 'InnovateTech Solutions',
                'current_position' => 'Founder & CEO',
                'current_location' => 'Bangalore, India',
                'current_salary' => 2500000.00,
                'bio' => 'Entrepreneur and innovator in the manufacturing technology space. Founded InnovateTech Solutions which now employs 100+ people.',
                'testimonial' => 'The entrepreneurial spirit fostered at Shantineketan College inspired me to start my own company. The technical foundation and problem-solving skills I learned here were crucial for my success.',
                'linkedin_url' => 'https://linkedin.com/in/amitkumar',
                'website_url' => 'https://innovatetech.com',
                'achievements' => ['Forbes 30 Under 30 2022', 'Startup of the Year Award 2021', 'Patent holder for 3 innovations'],
                'skills' => ['Entrepreneurship', 'Product Development', 'Team Leadership', 'Manufacturing', 'Innovation'],
                'is_featured' => true,
                'is_active' => true,
                'show_contact' => false,
                'available_for_mentoring' => true,
                'experience_years' => 6,
                'industry' => 'Manufacturing',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Sneha Gupta',
                'email' => 'sneha.gupta@infosys.com',
                'phone' => '+91 65432 10987',
                'student_id' => 'SNC2018004',
                'course' => 'B.Tech',
                'branch' => 'Information Technology',
                'passing_year' => 2022,
                'admission_year' => 2018,
                'current_company' => 'Infosys',
                'current_position' => 'Software Developer',
                'current_location' => 'Pune, India',
                'current_salary' => 800000.00,
                'bio' => 'Fresh graduate working on cutting-edge web technologies and mobile applications. Passionate about user experience and clean code.',
                'testimonial' => 'The hands-on approach to learning at Shantineketan College prepared me well for the industry. The placement support was excellent.',
                'linkedin_url' => 'https://linkedin.com/in/snehagupta',
                'achievements' => ['Best Final Year Project Award', 'Infosys Mysore Topper', 'Hackathon Winner 2021'],
                'skills' => ['Java', 'React', 'Node.js', 'MongoDB', 'AWS'],
                'is_featured' => false,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => false,
                'experience_years' => 2,
                'industry' => 'Information Technology',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Rajesh Verma',
                'email' => 'rajesh.verma@wipro.com',
                'phone' => '+91 54321 09876',
                'student_id' => 'SNC2015005',
                'course' => 'M.Tech',
                'branch' => 'Computer Science Engineering',
                'passing_year' => 2017,
                'admission_year' => 2015,
                'current_company' => 'Wipro',
                'current_position' => 'Technical Lead',
                'current_location' => 'Bangalore, India',
                'current_salary' => 1500000.00,
                'bio' => 'Technical lead with expertise in enterprise software development and team management. Specialized in Java technologies and microservices.',
                'testimonial' => 'The M.Tech program provided deep technical knowledge and research experience that helped me advance quickly in my career.',
                'linkedin_url' => 'https://linkedin.com/in/rajeshverma',
                'achievements' => ['Wipro Technical Excellence Award', 'Certified Scrum Master', 'Led team of 15 developers'],
                'skills' => ['Java', 'Spring Boot', 'Microservices', 'Docker', 'Kubernetes', 'Team Leadership'],
                'is_featured' => false,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => true,
                'experience_years' => 7,
                'industry' => 'Information Technology',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Kavya Singh',
                'email' => 'kavya.singh@deloitte.com',
                'phone' => '+91 43210 98765',
                'student_id' => 'SNC2016006',
                'course' => 'B.Com',
                'branch' => 'Accounting & Finance',
                'passing_year' => 2019,
                'admission_year' => 2016,
                'current_company' => 'Deloitte',
                'current_position' => 'Senior Consultant',
                'current_location' => 'Delhi, India',
                'current_salary' => 1100000.00,
                'bio' => 'Financial consultant specializing in audit and risk management. Working with Fortune 500 companies on financial compliance.',
                'testimonial' => 'The commerce program at Shantineketan College provided strong fundamentals in accounting and finance that are essential in my consulting career.',
                'linkedin_url' => 'https://linkedin.com/in/kavyasingh',
                'achievements' => ['CA Qualified', 'Deloitte Rising Star 2021', 'Published articles on financial compliance'],
                'skills' => ['Financial Analysis', 'Audit', 'Risk Management', 'SAP', 'Advanced Excel'],
                'is_featured' => false,
                'is_active' => true,
                'show_contact' => false,
                'available_for_mentoring' => true,
                'experience_years' => 5,
                'industry' => 'Financial Services',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Arjun Reddy',
                'email' => 'arjun@techstartup.com',
                'phone' => '+91 32109 87654',
                'student_id' => 'SNC2017007',
                'course' => 'BBA',
                'branch' => 'Marketing',
                'passing_year' => 2020,
                'admission_year' => 2017,
                'current_company' => 'TechStartup Inc',
                'current_position' => 'Marketing Manager',
                'current_location' => 'Gurgaon, India',
                'current_salary' => 900000.00,
                'bio' => 'Digital marketing expert with experience in growth hacking and brand building for tech startups.',
                'testimonial' => 'The BBA program gave me comprehensive business knowledge and the confidence to work in the fast-paced startup environment.',
                'linkedin_url' => 'https://linkedin.com/in/arjunreddy',
                'twitter_url' => 'https://twitter.com/arjunreddy',
                'achievements' => ['Increased company revenue by 300%', 'Google Ads Certified', 'Speaker at marketing conferences'],
                'skills' => ['Digital Marketing', 'Growth Hacking', 'SEO/SEM', 'Analytics', 'Brand Management'],
                'is_featured' => false,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => false,
                'experience_years' => 4,
                'industry' => 'Marketing',
                'verified_at' => Carbon::now(),
            ],
            [
                'name' => 'Meera Joshi',
                'email' => 'meera.joshi@accenture.com',
                'phone' => '+91 21098 76543',
                'student_id' => 'SNC2019008',
                'course' => 'Diploma in Computer Science',
                'branch' => 'Software Development',
                'passing_year' => 2022,
                'admission_year' => 2019,
                'current_company' => 'Accenture',
                'current_position' => 'Associate Software Engineer',
                'current_location' => 'Chennai, India',
                'current_salary' => 600000.00,
                'bio' => 'Recent graduate passionate about software development and emerging technologies. Quick learner with strong problem-solving skills.',
                'testimonial' => 'The diploma program provided practical skills and industry exposure that helped me land a job at a top consulting firm.',
                'linkedin_url' => 'https://linkedin.com/in/meerajoshi',
                'achievements' => ['Best Diploma Student 2022', 'Accenture Fast Track Program', 'Coding Competition Winner'],
                'skills' => ['Python', 'Java', 'Web Development', 'Database Management', 'Agile'],
                'is_featured' => false,
                'is_active' => true,
                'show_contact' => true,
                'available_for_mentoring' => false,
                'experience_years' => 2,
                'industry' => 'Information Technology',
                'verified_at' => Carbon::now(),
            ],
        ];

        foreach ($alumni as $alumnus) {
            Alumni::create($alumnus);
        }
    }
}
